version: '3.1'

services:

  db:
    image: "mariadb:10.3"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./conf/mariadb:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: "Happy888"
    networks:
       - lnmp-network
       
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
       - lnmp-network
       
  php:
#    image: php:5.6-fpm-alpine
    build: ./php/php56/
    restart: always
    ports:
      - "9000:9000"
    volumes:
     - ./site/:/var/www/html/:rw
     - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
     - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
     - ./log/php-fpm/:/var/log/php-fpm/:rw
    networks:
      - lnmp-network

#  php56:
#    build: ./php/php56/
##    image: "dockette/php:5.6-fpm"
#    restart: always
##    privileged: true
#    ports:
#      - "9000:9000"
#    volumes:
#      - ./site/:/srv/:rw
#      - ./conf/php/custom.ini:/etc/php/5.6/fpm/conf.d/991-custom.ini:rw
#      - ./log/php-fpm/:/var/log/php-fpm/:rw
#    environment:
#       TZ: "Asia/Shanghai"
#    networks:
#       - lnmp-network
       
  nginx:
    image: "nginx:alpine"
    restart: always
    ports:
       - "8880:80"
       - "8843:443"
#    privileged: true
    volumes:
      - ./site/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    networks:
       - lnmp-network
       
networks:
  lnmp-network:
    driver: bridge