version: '3.1'

services:

  db:
    image: "mariadb:10.3"
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - ./conf/mariadb:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: "Happy888"
      TZ: "Asia/Shanghai"
    networks:
       - lnmp-network
       
  adminer:
    image: adminer
    restart: always
    ports:
      - 8881:8080
    environment:
      TZ: "Asia/Shanghai"
    networks:
       - lnmp-network
       
  php56:
    image: "dtstudio/php:5.6-fpm-alpine"
#    build: ./php/php56/
    restart: always
    volumes:
     - ./site/:/var/www/html/:rw
     - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
     - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
     - ./log/php-fpm/:/var/log/php-fpm/:rw
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - lnmp-network

  php73:
    image: "dtstudio/php:7.3-fpm-alpine"
#    build: ./php/php73/
    restart: always
    volumes:
     - ./site/:/var/www/html/:rw
     - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
     - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
     - ./log/php-fpm/:/var/log/php-fpm/:rw
    environment:
      TZ: "Asia/Shanghai"
    networks:
      - lnmp-network
       
  nginx:
    image: "nginx:alpine"
    restart: always
    ports:
       - "8880:80"
       - "8890:81"
       - "8843:443"
    volumes:
      - ./site/:/var/www/html/:rw
      - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/nginx/:rw
    environment:
      TZ: "Asia/Shanghai"
    networks:
       - lnmp-network
       
networks:
  lnmp-network:
    driver: bridge