version: '3.1'

services:

  db:
    image: "mariadb:10.3"
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "Happy888"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080